require 'rubygems'
require 'cucumber'
require 'cucumber/rake/task'

#Cucumber::Rake::Task.new(:features) do |t|
  #t.profile = 'default'
#end

#task :default => :features

Cucumber::Rake::Task.new(:run) do |task|
  task.searching_on_hayneedle = ["features"]
end